name: GGymPeacekeeper
version: '1.0-SNAPSHOT'
main: me.ggym.Peacekeeper
api-version: '1.21'
depend: [Vault]
commands:
  status:
    description: "Показывает статус игрока (PvP или Мирный)"
    usage: "/status <nickname>"
  setstatus:
    description: "Позволяет задать статус игрока"
    usage: "/setstatus <PvP/Peace> <nickname>"
permissions:
  status.peace:
    description: "Режим мирного"
    default: false
  status.pvp:
    description: "Режим PvP"
    default: false
  status.admin:
    description: "Возможность редактировать статусы других игроков"
    default: false
  status.edit:
    description: "Возможность редактировать свой статус"
    default: false
  status.conversion:
    description: "Статус меняется"
    default: false